// Generated by Wrangler by running `wrangler types`

interface Env {
	DB: D1Database;
  SITE_TITLE: string;
  SITE_DESCRIPTION: string;
  SITE_KEYWORDS: string;
  SITE_URL: string;
  ENABLE_COPYRIGHT: boolean;
  ENABLE_POWERED_BY: boolean;
  FRIEND_LINKS_TITLE: string;
  FRIEND_LINKS_DESCRIPTION: string;
  AVATAR_URL: string;
}
